/** Desktop authorization transport for the selected server origin. Secret-bearing results stay in the main process. */

import { concreteGroup as validateConcreteGroup } from './group-policy.ts'

/** Public native-client identifier, never a client secret. */
export const HALLUCODEX_CLIENT_ID = 'hallucodex-desktop'

/** Stable, non-secret failures suitable for renderer status projection. */
export type AuthErrorCode = 'cancelled' | 'expired' | 'network_error' | 'invalid_response' | 'invalid_grant'
  | 'access_denied' | 'secure_storage_unavailable' | 'storage_error' | 'group_invalid' | 'signed_out'

/** Sanitized failure; neither server messages nor transport exceptions are retained. */
export class HalluCodexAuthError extends Error {
  /** Stable category safe for renderer status and diagnostics. */
  readonly code: AuthErrorCode

  constructor(code: AuthErrorCode) {
    super(code)
    this.name = 'HalluCodexAuthError'
    this.code = code
  }
}

/** Minimal account display fields; contains no credentials or privileged claims. */
export interface HalluCodexProfile {
  id: string
  displayName: string
}

/** Encrypted-at-rest refresh record; access tokens must never be added here. */
export interface RefreshGrant {
  refreshToken: string
  refreshExpiresAt: number
  deviceSessionId: string
  profile: HalluCodexProfile
  group: string
}

/** Validated server grant, held only by the account broker. */
export interface AccessGrant extends RefreshGrant {
  accessToken: string
  accessExpiresAt: number
  allowedGroups: string[]
}

/** PKCE authorization registration; all fields are generated by trusted main-process code. */
export interface AuthorizationRequest {
  state: string
  codeChallenge: string
  redirectUri: string
  deviceName: string
}

/** Code redemption is bound to the original callback and verifier. */
export interface CodeExchange {
  code: string
  codeVerifier: string
  redirectUri: string
}

/** Main-process network seam. Implementations must not log arguments or return secrets to a renderer. */
export interface HalluCodexAuthTransport {
  /**
   * Register a browser approval request.
   * @param request - Main-process-generated PKCE and callback fields.
   * @param signal - Current login cancellation.
   * @returns The pinned approval URL and opaque authorization request ID.
   */
  authorize(request: AuthorizationRequest, signal: AbortSignal): Promise<{ authorizationUrl: string; requestId: string }>
  /**
   * Redeem one code without automatically retrying it.
   * @param request - Code and original PKCE verifier/callback.
   * @param signal - Current login cancellation.
   * @returns A validated main-process-only grant.
   */
  exchange(request: CodeExchange, signal: AbortSignal): Promise<AccessGrant>
  /**
   * Rotate a refresh credential without automatically retrying it.
   * @param grant - Saved refresh credential and original identity binding.
   * @param signal - Account-generation cancellation.
   * @returns A validated successor grant, still subject to broker identity checks.
   */
  refresh(grant: RefreshGrant, signal: AbortSignal): Promise<AccessGrant>
  /**
   * Cancel an unconsumed request using its PKCE verifier.
   * @param requestId - Opaque authorization request ID.
   * @param codeVerifier - Original PKCE verifier proving ownership of the request.
   */
  cancel(requestId: string, codeVerifier: string): Promise<void>
  /**
   * Revoke the current family after local logout has already taken effect.
   * @param refreshToken - Current refresh credential, never a user-selected account ID.
   */
  revoke(refreshToken: string): Promise<void>
}

const allowedScopes = new Set(['relay:invoke', 'profile:read', 'balance:read', 'models:read', 'groups:read', 'group:select'])
const requiredScopes = ['relay:invoke', 'profile:read', 'balance:read', 'models:read', 'groups:read']

/**
 * Reject implicit inheritance and automatic cross-group routing.
 * @param value - A group from an untrusted wire response or stored record.
 * @returns The concrete group identifier.
 */
export function concreteGroup(value: unknown): string {
  try { return validateConcreteGroup(value) }
  catch (_error) { throw new HalluCodexAuthError('group_invalid') }
}

function record(value: unknown): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new HalluCodexAuthError('invalid_response')
  return value as Record<string, unknown>
}

function text(value: unknown, max = 8192, allowEmpty = false): string {
  if (typeof value !== 'string' || (!allowEmpty && value.length === 0) || value.length > max || /[\u0000-\u001f\u007f]/u.test(value)) {
    throw new HalluCodexAuthError('invalid_response')
  }
  return value
}

function credential(value: unknown, prefix: string, max = 8192): string {
  const result = text(value, max)
  if (!result.startsWith(prefix) || result.length <= prefix.length || !/^[A-Za-z0-9._~-]+$/u.test(result)) {
    throw new HalluCodexAuthError('invalid_response')
  }
  return result
}

/**
 * Validate the persisted refresh-only record, which is bound to the server origin that issued it.
 * @param value - Parsed decrypted JSON.
 * @param origin - Currently selected server origin.
 * @returns A newly projected record without additional persisted fields.
 */
export function parseRefreshRecord(value: unknown, origin: string): RefreshGrant {
  const data = record(value)
  const profile = record(data.profile)
  if (data.version !== 1 || data.origin !== origin || typeof data.refreshExpiresAt !== 'number'
    || !Number.isSafeInteger(data.refreshExpiresAt) || data.refreshExpiresAt <= 0) throw new HalluCodexAuthError('invalid_response')
  return {
    refreshToken: credential(data.refreshToken, 'dsr.'), refreshExpiresAt: data.refreshExpiresAt,
    deviceSessionId: text(data.deviceSessionId, 256), group: concreteGroup(data.group),
    profile: { id: text(profile.id, 256), displayName: text(profile.displayName, 256, true) },
  }
}

/** Server clocks commonly differ from desktop clocks by seconds; the server sets the absolute expiry. */
const CLOCK_SKEW_MS = 10 * 60 * 1000

/**
 * Validate and minimize a desktop token response; absolute refresh expiry uses Unix seconds on the wire.
 * @param value - Untrusted JSON token response.
 * @param now - Current Unix milliseconds on the desktop clock.
 * @returns A memory-only grant whose concrete group is explicitly server-allowed.
 */
export function parseAccessGrant(value: unknown, now: number): AccessGrant {
  const data = record(value)
  const profile = record(data.profile)
  if (data.token_type !== 'Bearer' || typeof data.expires_in !== 'number' || !Number.isSafeInteger(data.expires_in)
    || data.expires_in <= 0 || data.expires_in > 900 || typeof data.refresh_expires_at !== 'number'
    || !Number.isSafeInteger(data.refresh_expires_at) || data.refresh_expires_at * 1000 <= now
    || data.refresh_expires_at * 1000 > now + 30 * 24 * 60 * 60 * 1000 + CLOCK_SKEW_MS) throw new HalluCodexAuthError('invalid_response')
  const scope = text(data.scope, 256).split(' ')
  if (scope.some(item => !allowedScopes.has(item)) || requiredScopes.some(item => !scope.includes(item))) throw new HalluCodexAuthError('invalid_response')
  if (!Array.isArray(data.allowed_groups) || data.allowed_groups.length > 1024) throw new HalluCodexAuthError('group_invalid')
  const allowedGroups = data.allowed_groups.map(concreteGroup)
  const group = concreteGroup(data.group)
  if (!allowedGroups.includes(group)) throw new HalluCodexAuthError('group_invalid')
  return {
    accessToken: credential(data.access_token, 'dsk.', 16384), accessExpiresAt: now + data.expires_in * 1000,
    refreshToken: credential(data.refresh_token, 'dsr.'), refreshExpiresAt: data.refresh_expires_at * 1000,
    deviceSessionId: text(data.device_session_id, 256), group, allowedGroups,
    profile: { id: text(profile.id, 256), displayName: text(profile.display_name, 256, true) },
  }
}

/**
 * Pin browser approval navigation to the selected server origin and its dedicated authorization page.
 * @param value - Untrusted authorization URL returned by the API.
 * @param origin - Currently selected server origin.
 * @returns The validated URL, without accepting alternate hosts.
 */
export function authorizationUrl(value: unknown, origin: string): string {
  let url: URL
  try { url = new URL(text(value, 4096)) }
  catch (_error) { throw new HalluCodexAuthError('invalid_response') }
  if (url.origin !== origin || url.username || url.password || url.hash || url.pathname !== '/desktop/authorize') {
    throw new HalluCodexAuthError('invalid_response')
  }
  return url.href
}

/** HTTP(S) implementation with fixed endpoints on the selected origin, no cookies, redirects, or retries. */
export class HalluCodexHttpAuthTransport implements HalluCodexAuthTransport {
  /**
   * @param origin - Reads the currently selected server origin for every request.
   * @param fetcher - Network implementation.
   * @param now - Desktop clock in Unix milliseconds.
   */
  constructor(
    private readonly origin: () => string,
    private readonly fetcher: typeof fetch = fetch,
    private readonly now: () => number = Date.now,
  ) {}

  async authorize(request: AuthorizationRequest, signal: AbortSignal): Promise<{ authorizationUrl: string; requestId: string }> {
    const data = record(await this.post('/authorization-requests', {
      client_id: HALLUCODEX_CLIENT_ID, redirect_uri: request.redirectUri, state: request.state,
      code_challenge: request.codeChallenge, code_challenge_method: 'S256', device_name: request.deviceName,
      scope: requiredScopes.join(' '),
    }, signal))
    return { authorizationUrl: authorizationUrl(data.authorization_url, this.origin()), requestId: credential(data.request_id, 'dar.', 256) }
  }

  async exchange(request: CodeExchange, signal: AbortSignal): Promise<AccessGrant> {
    return parseAccessGrant(await this.post('/token', {
      grant_type: 'authorization_code', client_id: HALLUCODEX_CLIENT_ID, code: request.code,
      code_verifier: request.codeVerifier, redirect_uri: request.redirectUri,
    }, signal), this.now())
  }

  async refresh(grant: RefreshGrant, signal: AbortSignal): Promise<AccessGrant> {
    return parseAccessGrant(await this.post('/token', {
      grant_type: 'refresh_token', client_id: HALLUCODEX_CLIENT_ID, refresh_token: grant.refreshToken,
    }, signal), this.now())
  }

  async cancel(requestId: string, codeVerifier: string): Promise<void> {
    await this.post(`/authorization-requests/${encodeURIComponent(requestId)}/cancel`, { code_verifier: codeVerifier })
  }

  async revoke(refreshToken: string): Promise<void> {
    await this.post('/revoke', { refresh_token: refreshToken, client_id: HALLUCODEX_CLIENT_ID })
  }

  private async post(path: string, body: object, signal?: AbortSignal): Promise<unknown> {
    const timeout = AbortSignal.timeout(15_000)
    try {
      const response = await this.fetcher(`${this.origin()}/api/desktop/v1${path}`, {
        method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
        body: JSON.stringify(body), signal: signal ? AbortSignal.any([signal, timeout]) : timeout,
        redirect: 'error', credentials: 'omit', cache: 'no-store',
      })
      if (response.status >= 500 || response.status === 429 || response.status === 408) {
        await response.body?.cancel()
        throw new HalluCodexAuthError('network_error')
      }
      if (response.status === 204 && response.ok) return null
      if (!(response.headers.get('content-type') ?? '').toLowerCase().includes('application/json') || !response.body) {
        throw new HalluCodexAuthError('invalid_response')
      }
      const reader = response.body.getReader()
      const chunks: Uint8Array[] = []
      let length = 0
      try {
        while (true) {
          const next = await reader.read()
          if (next.done) break
          length += next.value.byteLength
          if (length > 262_144) throw new HalluCodexAuthError('invalid_response')
          chunks.push(next.value)
        }
      } finally {
        await reader.cancel()
      }
      let value: unknown
      try { value = JSON.parse(Buffer.concat(chunks).toString('utf8')) }
      catch (_error) { throw new HalluCodexAuthError('invalid_response') }
      if (!response.ok) {
        const data = record(value)
        const error = typeof data.error === 'object' && data.error !== null ? record(data.error).code : data.error
        const code = error ?? data.code
        if (code === 'invalid_grant') throw new HalluCodexAuthError(code)
        // An unavailable server, including one that predates desktop authorization, must not erase a saved login.
        if (code === 'temporarily_unavailable') throw new HalluCodexAuthError('network_error')
        throw new HalluCodexAuthError('invalid_response')
      }
      return value
    } catch (error) {
      if (error instanceof HalluCodexAuthError) throw error
      throw new HalluCodexAuthError(signal?.aborted ? 'cancelled' : 'network_error')
    }
  }
}
